name: tensorflow-ev
version: 'v1.3.0'
summary: An open-source software library for Machine Intelligence
description: |
  TensorFlow™ is an open source software library or numerical computation
  using data flow graphs. Nodes in the graph represent mathematical operations,
  while the graph edges represent the multidimensional data arrays (tensors)
  communicated between them. The flexible architecture allows you to deploy
  computation to one or more CPUs or GPUs in a desktop, server, or mobile device
  with a single API. TensorFlow was originally developed by researchers and
  engineers working on the Google Brain Team within Google's Machine Intelligence
  research organization for the purposes of conducting machine learning and deep
  neural networks research, but the system is general enough to be applicable in
  a wide variety of other domains as well.

grade: devel
confinement: devmode

apps:
  python:
    command: python

parts:
  tensorflow:
    source: https://github.com/tensorflow/tensorflow/archive/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: python
    python-version: python2
    python-packages:
      - six
      - numpy
    after: [bazel]
    build-packages:
      - wget
    install: |
      set -e
      PYTHON_BIN_PATH="$SNAPCRAFT_PART_INSTALL/usr/bin/python" \
      PYTHON_LIB_PATH="$SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages" \
      TF_NEED_MKL=0 \
      TF_NEED_JEMALLOC=1 \
      TF_NEED_GCP=0 \
      TF_NEED_HDFS=0 \
      TF_ENABLE_XLA=0 \
      TF_NEED_VERBS=0 \
      TF_NEED_OPENCL=0 \
      TF_NEED_CUDA=0 \
      TF_NEED_MPI=0 \
      CC_OPT_FLAGS="-march=native" \
        ./configure
      bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
      T=$(mktemp -d)
      bazel-bin/tensorflow/tools/pip_package/build_pip_package $T
      $SNAPCRAFT_PART_INSTALL/usr/bin/python -m pip install --prefix=$SNAPCRAFT_PART_INSTALL --no-compile $T/*.whl
  bazel:
    plugin: nil
    stage-packages:
      - unzip
    install: |
      BAZEL=bazel-0.5.4-installer-linux-x86_64.sh
      [ -e $BAZEL ] || wget https://github.com/bazelbuild/bazel/releases/download/0.5.4/$BAZEL
      chmod +x $BAZEL
      ./$BAZEL --prefix=$SNAPCRAFT_PART_INSTALL
