name: tensorflow-ev
version: 'v1.3.0'
summary: An open-source software library for Machine Intelligence
description: |
  TensorFlow™ is an open source software library or numerical computation
  using data flow graphs. Nodes in the graph represent mathematical operations,
  while the graph edges represent the multidimensional data arrays (tensors)
  communicated between them. The flexible architecture allows you to deploy
  computation to one or more CPUs or GPUs in a desktop, server, or mobile device
  with a single API. TensorFlow was originally developed by researchers and
  engineers working on the Google Brain Team within Google's Machine Intelligence
  research organization for the purposes of conducting machine learning and deep
  neural networks research, but the system is general enough to be applicable in
  a wide variety of other domains as well.

grade: devel
confinement: devmode

parts:
  tensorflow:
    source: https://github.com/tensorflow/tensorflow/archive/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: python
    python-version: python2
    after: [bazel]
    build-packages:
      - wget
    build: |
      set -e
      export PYTHONUSERBASE=$SNAPCRAFT_PART_INSTALL
      export PYTHONPATH=$SNAPCRAFT_PART_INSTALL/usr/lib/python2.7/site-packages
      pip install six numpy wheel

      PYTHON_BIN_PATH="$SNAPCRAFT_PART_INSTALL/usr/bin/python" \
      PYTHON_LIB_PATH="$SNAPCRAFT_PART_INSTALL/usr/lib/python2.7/dist-packages" \
      TF_NEED_MKL=0 \
      TF_NEED_JEMALLOC=1 \
      TF_NEED_GCP=0 \
      TF_NEED_HDFS=0 \
      TF_ENABLE_XLA=0 \
      TF_NEED_VERBS=0 \
      TF_NEED_OPENCL=0 \
      TF_NEED_CUDA=0 \
      TF_NEED_MPI=0 \
      CC_OPT_FLAGS="-march=native" \
        ./configure
      bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
      T=$(mktemp -d)
      bash -x bazel-bin/tensorflow/tools/pip_package/build_pip_package $T
      ls -la $T
      pip install $T/tensorflow-1.3.0-py2-none-any.whl
  bazel:
    plugin: nil
    stage-packages:
      - unzip
    install: |
      BAZEL=bazel-0.5.4-installer-linux-x86_64.sh
      [ -e $BAZEL ] || wget https://github.com/bazelbuild/bazel/releases/download/0.5.4/$BAZEL
      chmod +x $BAZEL
      ./$BAZEL --prefix=$SNAPCRAFT_PART_INSTALL
